drop_table_library:
    resource: "@DropTableLibraryBundle/Controller/"
    type:     annotation
    prefix:   /

#drop_table_user:
#    resource: "@DropTableUserBundle/Controller/"
#    type:     annotation
#    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook
